services:
  runner:
    image: luezhi11/github-runner:ubuntu20.04.2.322.0
    container_name: github-runner
    restart: always
    build:
      context: .
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
      GH_ORG: ${GH_ORG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
