services:
  runner:
    image: images.luezhi12.tech/github-runner:ubuntu20.04-linux-2.322.0
    restart: always
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_ORG: ${GH_ORG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
